swagger: '2.0'
info:
  version: '1.0'
  title: "AFFIXE2-MOBILE"
  description: Polls is a simple API allowing consumers to view polls and vote in them.
  license:
    name: MIT
    url: https://github.com/apiaryio/polls-api/blob/master/LICENSE
host: us-central1-affixe20mobile.cloudfunctions.net
basePath: /
schemes:
- https
consumes:
- application/json
produces:
- application/json
paths:
  /api/utilisateurs:
    x-summary: API Affixe Mobile
    post:
      description : Permet d'ajouter un nouvel utilisateur pour lui donner un accès à l'application.
      summary : Ajouter un utilisateur
      parameters :   
      - name: body
        in: body
        required: true
        schema:
          $ref: '#/definitions/User'
      responses:
        201:
          description: ''
          schema:
            $ref: '#/definitions/User'
definitions:
  User :
    title : User
    type : object
    properties:
      email :
        type: string
      password :
        type : string
      disabled : 
        type : boolean
      codeSite :
        type : string
      identifiant :
        type : string
    required :
      - email
      - password
      - disabled
      - codeSite
      - identifiant